### ISSUE TITLE
Rename project to JmeGradleTemplate

### ISSUE THREAD

**Issue by Ali-RS** [Monkey-Droid/Cross-platform-template#14]
Hi @Scrappers-glitch 

What do you think of renaming this project to JmeGradleTemplate? and adding the JME standard blue cube scene?

Just a suggestion

**Comment by Scrappers-glitch** [comment]
Hello @Ali-RS !

Thanks for your suggestions.



> What do you think of renaming this project to JmeGradleTemplate?

Give me some time to think of this; because this is a little bit different than a regular jme template produced by jme-sdk for example.



> adding the JME standard blue cube scene?

I would like to keep an asset aspect on the template, so that is why i am loading an asset model, this template should guide the developer to a universal game logic (but i am still working on this).
